name: scrape
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.12.1=h7934f7d_0
  - attrs=25.4.0=py314h06a4308_2
  - beautifulsoup4=4.14.3=py314h06a4308_0
  - blas=1.0=mkl
  - brotlicffi=1.2.0.0=py314h7354ed3_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2026.01.04=py314h06a4308_0
  - cffi=2.0.0=py314h4eded50_1
  - contourpy=1.3.3=py314hdb19cb5_0
  - cycler=0.12.1=py314h06a4308_0
  - cyrus-sasl=2.1.28=h83b0a09_4
  - dav1d=1.2.1=h5eee18b_0
  - expat=2.7.4=h7354ed3_0
  - fontconfig=2.15.0=h2c49b7f_0
  - fonttools=4.61.0=py314h47b2149_0
  - freetype=2.14.1=hf5b9546_0
  - fribidi=1.0.16=h9fb5f84_0
  - graphite2=1.3.14=h295c915_1
  - h11=0.16.0=py314h06a4308_1
  - harfbuzz=12.3.0=h79d275a_1
  - icu=73.1=h6a678d5_0
  - idna=3.11=py314h06a4308_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - jpeg=9f=h5ce9db8_0
  - kiwisolver=1.4.9=py314h24d9097_0
  - lcms2=2.17=heab6991_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libavif=1.3.0=h3539ee5_0
  - libcups=2.4.15=hbe4054b_0
  - libdeflate=1.22=h5eee18b_0
  - libdrm=2.4.124=h5eee18b_0
  - libegl=1.7.0=h5eee18b_2
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.7.4=h7354ed3_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgl=1.7.0=h5eee18b_2
  - libglib=2.86.3=h8b17d9a_0
  - libglvnd=1.7.0=h5eee18b_2
  - libglx=1.7.0=h5eee18b_2
  - libgomp=15.2.0=h4751f2c_7
  - libhwloc=2.12.1=default_hf1bbc79_1000
  - libiconv=1.16=h5eee18b_3
  - libkrb5=1.22.1=h6d2bf13_0
  - libllvm15=15.0.7=he89c38a_4
  - libmpdec=4.0.0=h5eee18b_0
  - libopengl=1.7.0=h5eee18b_2
  - libopenjpeg=2.5.4=hee96239_1
  - libpciaccess=0.18=h5eee18b_0
  - libpng=1.6.54=hee55ce4_0
  - libpq=17.6=h5ca1609_1
  - libsodium=1.0.20=heac8642_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtiff=4.7.1=h029b1ac_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.6.0=hb7bb969_0
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - lmdb=0.9.31=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib=3.10.8=py314h06a4308_0
  - matplotlib-base=3.10.8=py314h54cb298_0
  - mesalib=25.1.5=h31e3550_0
  - mkl=2025.0.0=hacee8c2_941
  - mkl-service=2.5.2=py314hacdc0fc_0
  - mkl_fft=2.1.1=py314h2be417e_0
  - mkl_random=1.3.0=py314hda4e5d8_0
  - mysql-common=9.3.0=h9e076cb_4
  - mysql-libs=9.3.0=h6ecde68_4
  - ncurses=6.5=h7934f7d_0
  - numpy=2.4.2=py314hc4ca38b_0
  - numpy-base=2.4.2=py314h7c74580_0
  - openldap=2.6.12=hb446bd0_0
  - openssl=3.0.19=h1b28b03_0
  - outcome=1.3.0=py314h06a4308_0
  - packaging=25.0=py314h06a4308_1
  - pandas=3.0.0=py314h973aee8_0
  - pcre2=10.46=hf426167_0
  - pillow=12.1.0=py314hd9fd23a_0
  - pip=26.0.1=pyhc872135_0
  - pixman=0.46.4=h7934f7d_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pyparsing=3.2.5=py314h06a4308_0
  - pyqt=6.9.1=py314h43fb04a_0
  - pyqt6-sip=13.10.2=py314hee96239_0
  - pysocks=1.7.1=py314h06a4308_1
  - python=3.14.2=h90eec9f_101_cp314
  - python-dateutil=2.9.0post0=py314h06a4308_2
  - python_abi=3.14=2_cp314
  - qtbase=6.9.2=h1fa0d2d_6
  - qtdeclarative=6.9.2=h55666de_1
  - qtsvg=6.9.2=h75a08ff_1
  - qttools=6.9.2=hc856bc8_1
  - qtwayland=6.9.2=h9f1b7ec_1
  - qtwebchannel=6.9.2=hbdd6827_1
  - qtwebsockets=6.9.2=hbdd6827_1
  - readline=8.3=hc2a1206_0
  - seaborn=0.13.2=py314h06a4308_3
  - selenium=4.38.0=py314h828f358_0
  - setuptools=80.10.2=py314h06a4308_0
  - sip=6.12.0=py314h695c4d2_0
  - six=1.17.0=py314h06a4308_0
  - sniffio=1.3.1=py314h06a4308_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.5=py314h06a4308_0
  - spirv-tools=2025.1=hdb19cb5_0
  - sqlite=3.51.1=he0a8d7e_0
  - tbb=2022.3.0=h698db13_0
  - tbb-devel=2022.3.0=h698db13_0
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.4=py314h47b2149_0
  - trio=0.32.0=py314h06a4308_0
  - trio-websocket=0.12.2=py314h06a4308_1
  - typing-extensions=4.15.0=py314h06a4308_0
  - typing_extensions=4.15.0=py314h06a4308_0
  - tzdata=2025c=he532380_0
  - urllib3=2.6.3=py314h06a4308_0
  - wayland=1.24.0=hdac8c69_0
  - websocket-client=1.8.0=py314h06a4308_0
  - wheel=0.46.3=py314h06a4308_0
  - wsproto=1.3.1=py314h06a4308_0
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.1=h5eee18b_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.2=h5eee18b_0
  - xkeyboard-config=2.44=h382ed1a_1
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-libxrandr=1.5.4=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxshmfence=1.3.3=h9b100fa_0
  - xorg-libxxf86vm=1.1.6=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
prefix: /home/philex/anaconda3/envs/scrape
